name: stack_overflow
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.2+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  intl: ^0.18.0
  date_field: ^5.0.1
  dartz: ^0.10.1
  retry: ^3.1.2
  connectivity_plus: ^6.0.2
  better_player: ^0.0.83
  just_audio: ^0.9.37
  audio_session: ^0.1.19
  scrollable_list_tab_scroller: ^0.2.0
  tutorial_coach_mark: ^1.2.11
  internet_connection_checker_plus: ^2.4.2
  mobile_scanner: ^5.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  get_it: ^7.7.0
  
  azlistview: 
    git: 
      url: https://github.com/ramkshukla/azlistview.git
      ref: master
  
  firebase_core: ^3.1.0
  otp_text_field: ^1.1.3
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.0.1
  firebase_app_check: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
